/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommenders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recommenders */
        get: operations["list_recommenders_recommenders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orchestrator/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run All */
        post: operations["run_all_orchestrator_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommenders/{name}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run One */
        post: operations["run_one_recommenders__name__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/features/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Features */
        post: operations["run_features_features_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recs */
        get: operations["list_recs_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations/{rec_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rec */
        get: operations["get_rec_recommendations__rec_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations/{rec_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept */
        post: operations["accept_recommendations__rec_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations/{rec_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject */
        post: operations["reject_recommendations__rec_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/autonomous/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Autonomous List */
        get: operations["autonomous_list_autonomous_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/autonomous/config/{action_type}/{warehouse_name}/{knob}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Autonomous Upsert */
        put: operations["autonomous_upsert_autonomous_config__action_type___warehouse_name___knob__put"];
        post?: never;
        /** Autonomous Delete */
        delete: operations["autonomous_delete_autonomous_config__action_type___warehouse_name___knob__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/autonomous/config/{action_type}/{warehouse_name}/{knob}/reset-circuit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autonomous Reset Circuit */
        post: operations["autonomous_reset_circuit_autonomous_config__action_type___warehouse_name___knob__reset_circuit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/autonomous/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Autonomous Applications */
        get: operations["autonomous_applications_autonomous_applications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/autonomous/applications/{application_id}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autonomous Rollback */
        post: operations["autonomous_rollback_autonomous_applications__application_id__rollback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/warehouses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Warehouses */
        get: operations["list_warehouses_warehouses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Credentials */
        get: operations["get_credentials_credentials_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/credentials/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Credentials */
        post: operations["verify_credentials_credentials_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Seed */
        post: operations["seed_seed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AutonomousApplicationOut */
        AutonomousApplicationOut: {
            /** Id */
            id: number;
            /** Recommendation Id */
            recommendation_id: number;
            /** Action Type */
            action_type: string;
            /** Warehouse Name */
            warehouse_name: string | null;
            /** Applied Sql */
            applied_sql: string;
            /** Rollback Sql */
            rollback_sql: string | null;
            /**
             * Applied At
             * Format: date-time
             */
            applied_at: string;
            /** State */
            state: string;
            /** Error */
            error?: string | null;
            /** Rolled Back At */
            rolled_back_at?: string | null;
            /** Rolled Back Sql */
            rolled_back_sql?: string | null;
            /** Rollback Error */
            rollback_error?: string | null;
        };
        /** AutonomousConfigOut */
        AutonomousConfigOut: {
            /** Action Type */
            action_type: string;
            /** Warehouse Name */
            warehouse_name: string;
            /**
             * Knob
             * @default *
             */
            knob: string;
            /** Enabled */
            enabled: boolean;
            /** Confidence Threshold */
            confidence_threshold: number;
            /** Cooldown Hours */
            cooldown_hours: number;
            /** Max Rollbacks Per Week */
            max_rollbacks_per_week: number;
            /** Circuit Open Until */
            circuit_open_until?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** AutonomousConfigUpsert */
        AutonomousConfigUpsert: {
            /** Enabled */
            enabled?: boolean | null;
            /** Confidence Threshold */
            confidence_threshold?: number | null;
            /** Cooldown Hours */
            cooldown_hours?: number | null;
            /** Max Rollbacks Per Week */
            max_rollbacks_per_week?: number | null;
        };
        /**
         * CredentialStatusOut
         * @description Public-safe view of resolved credentials.  Never includes secrets.
         */
        CredentialStatusOut: {
            /** Configured */
            configured: boolean;
            /** Account */
            account?: string | null;
            /** User */
            user?: string | null;
            /** Role */
            role?: string | null;
            /** Warehouse */
            warehouse?: string | null;
            /** Auth Method */
            auth_method?: string | null;
            /** Source */
            source?: string | null;
            /** Private Key Path */
            private_key_path?: string | null;
        };
        /** CredentialVerifyOut */
        CredentialVerifyOut: {
            /** Ok */
            ok: boolean;
            /** Account */
            account?: string | null;
            /** User */
            user?: string | null;
            /** Role */
            role?: string | null;
            /** Warehouse */
            warehouse?: string | null;
            /** Region */
            region?: string | null;
            /** Error */
            error?: string | null;
        };
        /**
         * EvidenceRef
         * @description A pointer to data that supports this recommendation.
         */
        EvidenceRef: {
            /** Kind */
            kind: string;
            /** Description */
            description: string;
            /** Filters */
            filters?: {
                [key: string]: unknown;
            };
            /** Metric */
            metric?: string | null;
            /** Value */
            value?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Impact
         * @description Expected outcome if the recommendation is applied.
         */
        Impact: {
            /** Credits Delta Daily */
            credits_delta_daily?: number | null;
            /** P50 Latency Delta Ms */
            p50_latency_delta_ms?: number | null;
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
            /** Notes */
            notes?: string | null;
        };
        /** RecommendationOut */
        RecommendationOut: {
            /** Id */
            id: number | null;
            /** Generated By */
            generated_by: string;
            /** Action Type */
            action_type: string;
            /** Target Resource */
            target_resource: string | null;
            /** Preview */
            preview: string;
            /** Sql */
            sql: string;
            /** Rollback Sql */
            rollback_sql?: string | null;
            /** Rationale */
            rationale: string;
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            expected_impact: components["schemas"]["Impact"];
            status: components["schemas"]["RecommendationStatus"];
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Applied At */
            applied_at?: string | null;
        };
        /**
         * RecommendationStatus
         * @enum {string}
         */
        RecommendationStatus: "PROPOSED" | "ACCEPTED" | "REJECTED" | "APPLIED" | "ROLLED_BACK" | "SUPERSEDED";
        /** RecommenderInfo */
        RecommenderInfo: {
            /** Name */
            name: string;
            /** Version */
            version: string;
            /** Action Type */
            action_type: string;
            /** Class Path */
            class_path: string;
            /** Required Feature Tables */
            required_feature_tables?: string[];
        };
        /** RunRecommenderReport */
        RunRecommenderReport: {
            /** Name */
            name: string;
            /** Is Ready */
            is_ready: boolean;
            /** Readiness Reason */
            readiness_reason: string;
            /** Fit Completed */
            fit_completed: boolean;
            /**
             * Predictions Emitted
             * @default 0
             */
            predictions_emitted: number;
            /** Error */
            error?: string | null;
        };
        /** RunRequest */
        RunRequest: {
            /**
             * Skip Sync
             * @default true
             */
            skip_sync: boolean;
        };
        /** RunResponse */
        RunResponse: {
            /** Feature Results */
            feature_results: {
                [key: string]: unknown;
            }[];
            /** Recommender Results */
            recommender_results: components["schemas"]["RunRecommenderReport"][];
        };
        /** SeedRequest */
        SeedRequest: {
            /**
             * Days
             * @default 21
             */
            days: number;
            /**
             * Seed
             * @default 42
             */
            seed: number;
        };
        /** SourceFreshnessOut */
        SourceFreshnessOut: {
            /** Name */
            name: string;
            /** Rows */
            rows: number;
            /** Earliest */
            earliest?: string | null;
            /** Latest */
            latest?: string | null;
            /** Last Synced At */
            last_synced_at?: string | null;
        };
        /** StatusOut */
        StatusOut: {
            /** Sources */
            sources: components["schemas"]["SourceFreshnessOut"][];
            /** Warehouses */
            warehouses: components["schemas"]["WarehouseSummaryOut"][];
            /** Recommender States */
            recommender_states: {
                [key: string]: unknown;
            }[];
            /** Recommendation Counts */
            recommendation_counts: {
                [key: string]: number;
            };
        };
        /** StatusUpdateRequest */
        StatusUpdateRequest: {
            /** Note */
            note?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WarehouseSummaryOut */
        WarehouseSummaryOut: {
            /** Name */
            name: string;
            /** Size */
            size?: string | null;
            /** Auto Suspend Seconds */
            auto_suspend_seconds?: number | null;
            /** Auto Resume */
            auto_resume?: boolean | null;
            /**
             * Queries In Window
             * @default 0
             */
            queries_in_window: number;
            /**
             * Suspend Resume Events
             * @default 0
             */
            suspend_resume_events: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_recommenders_recommenders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommenderInfo"][];
                };
            };
        };
    };
    run_all_orchestrator_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_one_recommenders__name__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRecommenderReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_features_features_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: {
                            [key: string]: number | string;
                        }[];
                    };
                };
            };
        };
    };
    list_recs_recommendations_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["RecommendationStatus"];
                action_type?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rec_recommendations__rec_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rec_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_recommendations__rec_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rec_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StatusUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_recommendations__rec_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rec_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StatusUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    autonomous_list_autonomous_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutonomousConfigOut"][];
                };
            };
        };
    };
    autonomous_upsert_autonomous_config__action_type___warehouse_name___knob__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_type: string;
                warehouse_name: string;
                knob: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutonomousConfigUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutonomousConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    autonomous_delete_autonomous_config__action_type___warehouse_name___knob__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_type: string;
                warehouse_name: string;
                knob: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    autonomous_reset_circuit_autonomous_config__action_type___warehouse_name___knob__reset_circuit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_type: string;
                warehouse_name: string;
                knob: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    autonomous_applications_autonomous_applications_get: {
        parameters: {
            query?: {
                warehouse?: string | null;
                action_type?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutonomousApplicationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    autonomous_rollback_autonomous_applications__application_id__rollback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_warehouses_warehouses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarehouseSummaryOut"][];
                };
            };
        };
    };
    get_status_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOut"];
                };
            };
        };
    };
    get_credentials_credentials_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialStatusOut"];
                };
            };
        };
    };
    verify_credentials_credentials_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialVerifyOut"];
                };
            };
        };
    };
    seed_seed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SeedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
