/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarehousesRouteImport } from './routes/warehouses'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ExperimentsRouteImport } from './routes/experiments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WarehousesIndexRouteImport } from './routes/warehouses.index'
import { Route as ExperimentsIndexRouteImport } from './routes/experiments.index'
import { Route as WarehousesNameRouteImport } from './routes/warehouses.$name'
import { Route as ExperimentsIdRouteImport } from './routes/experiments.$id'

const WarehousesRoute = WarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsRoute = ExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehousesIndexRoute = WarehousesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WarehousesRoute,
} as any)
const ExperimentsIndexRoute = ExperimentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExperimentsRoute,
} as any)
const WarehousesNameRoute = WarehousesNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => WarehousesRoute,
} as any)
const ExperimentsIdRoute = ExperimentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ExperimentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experiments': typeof ExperimentsRouteWithChildren
  '/recommendations': typeof RecommendationsRoute
  '/settings': typeof SettingsRoute
  '/warehouses': typeof WarehousesRouteWithChildren
  '/experiments/$id': typeof ExperimentsIdRoute
  '/warehouses/$name': typeof WarehousesNameRoute
  '/experiments/': typeof ExperimentsIndexRoute
  '/warehouses/': typeof WarehousesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recommendations': typeof RecommendationsRoute
  '/settings': typeof SettingsRoute
  '/experiments/$id': typeof ExperimentsIdRoute
  '/warehouses/$name': typeof WarehousesNameRoute
  '/experiments': typeof ExperimentsIndexRoute
  '/warehouses': typeof WarehousesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/experiments': typeof ExperimentsRouteWithChildren
  '/recommendations': typeof RecommendationsRoute
  '/settings': typeof SettingsRoute
  '/warehouses': typeof WarehousesRouteWithChildren
  '/experiments/$id': typeof ExperimentsIdRoute
  '/warehouses/$name': typeof WarehousesNameRoute
  '/experiments/': typeof ExperimentsIndexRoute
  '/warehouses/': typeof WarehousesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/experiments'
    | '/recommendations'
    | '/settings'
    | '/warehouses'
    | '/experiments/$id'
    | '/warehouses/$name'
    | '/experiments/'
    | '/warehouses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/recommendations'
    | '/settings'
    | '/experiments/$id'
    | '/warehouses/$name'
    | '/experiments'
    | '/warehouses'
  id:
    | '__root__'
    | '/'
    | '/experiments'
    | '/recommendations'
    | '/settings'
    | '/warehouses'
    | '/experiments/$id'
    | '/warehouses/$name'
    | '/experiments/'
    | '/warehouses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperimentsRoute: typeof ExperimentsRouteWithChildren
  RecommendationsRoute: typeof RecommendationsRoute
  SettingsRoute: typeof SettingsRoute
  WarehousesRoute: typeof WarehousesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warehouses': {
      id: '/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof WarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments': {
      id: '/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof ExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouses/': {
      id: '/warehouses/'
      path: '/'
      fullPath: '/warehouses/'
      preLoaderRoute: typeof WarehousesIndexRouteImport
      parentRoute: typeof WarehousesRoute
    }
    '/experiments/': {
      id: '/experiments/'
      path: '/'
      fullPath: '/experiments/'
      preLoaderRoute: typeof ExperimentsIndexRouteImport
      parentRoute: typeof ExperimentsRoute
    }
    '/warehouses/$name': {
      id: '/warehouses/$name'
      path: '/$name'
      fullPath: '/warehouses/$name'
      preLoaderRoute: typeof WarehousesNameRouteImport
      parentRoute: typeof WarehousesRoute
    }
    '/experiments/$id': {
      id: '/experiments/$id'
      path: '/$id'
      fullPath: '/experiments/$id'
      preLoaderRoute: typeof ExperimentsIdRouteImport
      parentRoute: typeof ExperimentsRoute
    }
  }
}

interface ExperimentsRouteChildren {
  ExperimentsIdRoute: typeof ExperimentsIdRoute
  ExperimentsIndexRoute: typeof ExperimentsIndexRoute
}

const ExperimentsRouteChildren: ExperimentsRouteChildren = {
  ExperimentsIdRoute: ExperimentsIdRoute,
  ExperimentsIndexRoute: ExperimentsIndexRoute,
}

const ExperimentsRouteWithChildren = ExperimentsRoute._addFileChildren(
  ExperimentsRouteChildren,
)

interface WarehousesRouteChildren {
  WarehousesNameRoute: typeof WarehousesNameRoute
  WarehousesIndexRoute: typeof WarehousesIndexRoute
}

const WarehousesRouteChildren: WarehousesRouteChildren = {
  WarehousesNameRoute: WarehousesNameRoute,
  WarehousesIndexRoute: WarehousesIndexRoute,
}

const WarehousesRouteWithChildren = WarehousesRoute._addFileChildren(
  WarehousesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperimentsRoute: ExperimentsRouteWithChildren,
  RecommendationsRoute: RecommendationsRoute,
  SettingsRoute: SettingsRoute,
  WarehousesRoute: WarehousesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
