"""`sfo` CLI — drive the optimizer from a terminal."""
from __future__ import annotations

import click
from rich.console import Console
from rich.table import Table

from snowflake_optimizer.features import DEFAULT_TRANSFORMS
from snowflake_optimizer.features.base import FeaturePipeline
from snowflake_optimizer.orchestrator import Orchestrator
from snowflake_optimizer.recommendations import RecommendationStatus, RecommendationStore
from snowflake_optimizer.recommenders.registry import default_registry
from snowflake_optimizer.seed import seed_demo_data
from snowflake_optimizer.storage import get_connection

console = Console()


@click.group()
def cli() -> None:
    """sfo — locally-hosted Snowflake optimizer."""


@cli.command()
@click.option("--days", default=21, show_default=True, help="Days of synthetic history to generate")
def seed(days: int) -> None:
    """Clear raw.* and populate with synthetic demo data."""
    conn = get_connection()
    counts = seed_demo_data(conn, days=days)
    for tbl, n in counts.items():
        console.print(f"  {tbl}: {n} rows")
    console.print("[green]Seed complete.[/green]")


@cli.command()
@click.option("--skip-sync/--no-skip-sync", default=True,
              help="Skip Snowflake sync (default yes — assumes raw.* already populated)")
def run(skip_sync: bool) -> None:
    """Run features + recommenders and persist Recommendations."""
    conn = get_connection()
    pipeline = FeaturePipeline(DEFAULT_TRANSFORMS)
    registry = default_registry()
    orch = Orchestrator(conn, pipeline=pipeline, registry=registry)
    report = orch.run(skip_sync=skip_sync)

    console.print("[bold]Feature pipeline:[/bold]")
    for f in report.feature_results:
        console.print(f"  • {f.name}  ({f.duration_seconds:.3f}s)")

    console.print("\n[bold]Recommenders:[/bold]")
    for r in report.recommender_results:
        status = "ready" if r.is_ready else "training"
        err = f"  [red]error:[/red] {r.error}" if r.error else ""
        console.print(
            f"  • {r.name}: {status} — {r.readiness_reason}  "
            f"[blue]{r.predictions_emitted} proposal(s)[/blue]{err}"
        )


@cli.command("list")
@click.option("--status", type=click.Choice([s.value for s in RecommendationStatus]),
              default=RecommendationStatus.PROPOSED.value)
@click.option("--limit", default=50, show_default=True)
def list_recs(status: str, limit: int) -> None:
    """List recommendations."""
    conn = get_connection()
    store = RecommendationStore(conn)
    recs = store.list(status=RecommendationStatus(status), limit=limit)

    if not recs:
        console.print(f"[yellow]No recommendations with status={status}[/yellow]")
        return

    tbl = Table(show_header=True, header_style="bold")
    tbl.add_column("ID", justify="right")
    tbl.add_column("Type")
    tbl.add_column("Target")
    tbl.add_column("Proposal", max_width=40)
    tbl.add_column("Impact (credits/day)", justify="right")
    tbl.add_column("Confidence", justify="right")
    for r in recs:
        impact = r.expected_impact.credits_delta_daily
        impact_str = "—" if impact is None else f"{impact:+.2f}"
        tbl.add_row(
            str(r.id),
            r.action.type.value,
            r.action.target_resource() or "—",
            r.action.dry_run_preview().splitlines()[-1][:60],
            impact_str,
            f"{r.expected_impact.confidence:.2f}",
        )
    console.print(tbl)


@cli.command()
@click.argument("rec_id", type=int)
def show(rec_id: int) -> None:
    """Show full detail for one recommendation."""
    conn = get_connection()
    store = RecommendationStore(conn)
    rec = store.get(rec_id)
    if not rec:
        console.print(f"[red]No recommendation with id={rec_id}[/red]")
        raise SystemExit(1)

    console.rule(f"[bold]Recommendation #{rec.id}[/bold]")
    console.print(f"[bold]Generated by:[/bold] {rec.generated_by}")
    console.print(f"[bold]Status:[/bold] {rec.status.value}")
    console.print(f"[bold]Target:[/bold] {rec.action.target_resource()}")
    console.print()
    console.print("[bold]Preview[/bold]")
    console.print(rec.action.dry_run_preview())
    console.print()
    console.print("[bold]SQL to run[/bold]")
    console.print(f"[cyan]{rec.action.to_sql()}[/cyan]")
    if rec.rollback_sql or (hasattr(rec.action, "rollback_sql") and rec.action.rollback_sql()):  # type: ignore[attr-defined]
        rollback = rec.rollback_sql or rec.action.rollback_sql()  # type: ignore[attr-defined]
        console.print()
        console.print("[bold]Rollback[/bold]")
        console.print(f"[dim]{rollback}[/dim]")
    console.print()
    console.print("[bold]Rationale[/bold]")
    console.print(rec.rationale)
    console.print()
    console.print("[bold]Evidence[/bold]")
    for ev in rec.evidence:
        val = "" if ev.value is None else f"  value={ev.value}"
        console.print(f"  • [{ev.kind}] {ev.description}{val}")
    console.print()
    console.print("[bold]Expected impact[/bold]")
    console.print(rec.expected_impact.model_dump_json(indent=2))


@cli.command()
@click.argument("rec_id", type=int)
@click.option("--note", default=None)
def accept(rec_id: int, note: str | None) -> None:
    """Mark a recommendation ACCEPTED (advisory-only — does not execute)."""
    conn = get_connection()
    store = RecommendationStore(conn)
    if not store.get(rec_id):
        console.print(f"[red]No recommendation with id={rec_id}[/red]")
        raise SystemExit(1)
    store.set_status(rec_id, RecommendationStatus.ACCEPTED, notes=note)
    console.print(f"[green]#{rec_id} marked ACCEPTED.[/green]  "
                  f"Run `sfo show {rec_id}` then execute the SQL yourself.")


@cli.command()
@click.argument("rec_id", type=int)
@click.option("--note", default=None)
def reject(rec_id: int, note: str | None) -> None:
    """Mark a recommendation REJECTED."""
    conn = get_connection()
    store = RecommendationStore(conn)
    if not store.get(rec_id):
        console.print(f"[red]No recommendation with id={rec_id}[/red]")
        raise SystemExit(1)
    store.set_status(rec_id, RecommendationStatus.REJECTED, notes=note)
    console.print(f"[yellow]#{rec_id} marked REJECTED.[/yellow]")


@cli.command()
def ui() -> None:
    """Launch the Streamlit UI."""
    import subprocess
    import sys
    from pathlib import Path

    app_path = Path(__file__).parent / "ui" / "app.py"
    subprocess.run(
        [sys.executable, "-m", "streamlit", "run", str(app_path)],
        check=False,
    )


if __name__ == "__main__":
    cli()
