"""Streamlit UI — inbox-style recommendation review.

Left sidebar: global summary + filters + actions.
Main area: list of recommendations, then per-recommendation detail.
"""
from __future__ import annotations

import pandas as pd
import streamlit as st

from snowflake_optimizer.features import DEFAULT_TRANSFORMS
from snowflake_optimizer.features.base import FeaturePipeline
from snowflake_optimizer.orchestrator import Orchestrator
from snowflake_optimizer.recommendations import RecommendationStatus, RecommendationStore
from snowflake_optimizer.recommenders.registry import default_registry
from snowflake_optimizer.seed import seed_demo_data
from snowflake_optimizer.storage import get_connection


st.set_page_config(
    page_title="Snowflake Optimizer",
    page_icon="❄️",
    layout="wide",
)


# ---- Shared connection (one per Streamlit session) ----
@st.cache_resource
def _conn():
    return get_connection()


def _store() -> RecommendationStore:
    return RecommendationStore(_conn())


# ---- Sidebar ----
st.sidebar.title("❄️  Snowflake Optimizer")
st.sidebar.caption("Locally-hosted advisory v0.1")

with st.sidebar.expander("Data", expanded=False):
    st.caption(
        "Run a sync (requires Snowflake creds) or seed synthetic data to try the UI."
    )
    days = st.number_input("Seed days", min_value=7, max_value=60, value=21)
    if st.button("Seed synthetic data", use_container_width=True):
        counts = seed_demo_data(_conn(), days=int(days))
        st.success("Seeded: " + ", ".join(f"{k}={v}" for k, v in counts.items()))

    if st.button("Run features + recommenders", use_container_width=True):
        orch = Orchestrator(
            _conn(),
            pipeline=FeaturePipeline(DEFAULT_TRANSFORMS),
            registry=default_registry(),
        )
        report = orch.run(skip_sync=True)
        total_preds = sum(r.predictions_emitted for r in report.recommender_results)
        st.success(f"Run complete.  {total_preds} recommendation(s) emitted.")

status_filter = st.sidebar.selectbox(
    "Status",
    options=[s.value for s in RecommendationStatus],
    index=0,
)


# ---- Main ----
st.title("Recommendations")

store = _store()
recs = store.list(status=RecommendationStatus(status_filter), limit=200)

# Summary strip
col1, col2, col3, col4 = st.columns(4)
total_savings = sum(
    (r.expected_impact.credits_delta_daily or 0.0)
    for r in store.list(status=RecommendationStatus.PROPOSED, limit=500)
)
col1.metric("Open proposals",
            len(store.list(status=RecommendationStatus.PROPOSED, limit=500)))
col2.metric("Accepted", len(store.list(status=RecommendationStatus.ACCEPTED, limit=500)))
col3.metric("Rejected", len(store.list(status=RecommendationStatus.REJECTED, limit=500)))
col4.metric("Est. daily credit delta", f"{total_savings:+.2f}",
            help="Sum of expected_impact.credits_delta_daily across open proposals. "
                 "Negative values = credits saved.")

st.divider()

if not recs:
    st.info(f"No recommendations with status = {status_filter}.")
    st.stop()

# List as a table first
rows = []
for r in recs:
    rows.append({
        "id": r.id,
        "type": r.action.type.value,
        "target": r.action.target_resource() or "",
        "proposal": r.action.dry_run_preview().splitlines()[-1],
        "credits_delta_daily": r.expected_impact.credits_delta_daily,
        "confidence": r.expected_impact.confidence,
        "generated_by": r.generated_by,
    })
df = pd.DataFrame(rows)
st.dataframe(df, use_container_width=True, hide_index=True)

# Detail: pick one
rec_id = st.selectbox("Open a recommendation", options=[r.id for r in recs],
                       format_func=lambda x: f"#{x}")
rec = next(r for r in recs if r.id == rec_id)

st.subheader(f"#{rec.id} · {rec.action.type.value}")
st.caption(f"Generated by `{rec.generated_by}` · target `{rec.action.target_resource()}`")

c1, c2 = st.columns([2, 1])
with c1:
    st.markdown("**Preview**")
    st.code(rec.action.dry_run_preview(), language="text")

    st.markdown("**SQL to run**")
    st.code(rec.action.to_sql(), language="sql")

    rollback = getattr(rec.action, "rollback_sql", lambda: None)()
    if rollback:
        with st.expander("Rollback SQL"):
            st.code(rollback, language="sql")

    st.markdown("**Rationale**")
    st.write(rec.rationale)

    st.markdown("**Evidence**")
    for ev in rec.evidence:
        val = "" if ev.value is None else f"  —  **{ev.metric or 'value'}**: `{ev.value}`"
        st.markdown(f"- *{ev.kind}* · {ev.description}{val}")

with c2:
    st.markdown("**Expected impact**")
    impact = rec.expected_impact
    if impact.credits_delta_daily is not None:
        label = "savings" if impact.credits_delta_daily < 0 else "added cost"
        st.metric(f"Daily credit {label}",
                  f"{abs(impact.credits_delta_daily):.2f}")
    st.metric("Confidence", f"{impact.confidence:.0%}")
    if impact.notes:
        st.caption(impact.notes)

    st.divider()

    if rec.status == RecommendationStatus.PROPOSED:
        note = st.text_input("Note (optional)", key=f"note_{rec.id}")
        b1, b2 = st.columns(2)
        if b1.button("✅ Accept", key=f"acc_{rec.id}", use_container_width=True):
            store.set_status(rec.id, RecommendationStatus.ACCEPTED, notes=note or None)
            st.success("Accepted.  Execute the SQL yourself when ready.")
            st.rerun()
        if b2.button("❌ Reject", key=f"rej_{rec.id}", use_container_width=True):
            store.set_status(rec.id, RecommendationStatus.REJECTED, notes=note or None)
            st.warning("Rejected.")
            st.rerun()
    else:
        st.info(f"Status: **{rec.status.value}**")
