/**
 * Side-drawer that shows the full detail of one recommendation.
 *
 * Driven by an id (number | null).  Pass `onOpenChange` to close — typically
 * clears the URL search param so the back button works.
 *
 * Used by /recommendations and (eventually) anywhere a rec is referenced.
 */
import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { Link } from '@tanstack/react-router'
import {
  AlertCircle, Check, ChevronDown, ChevronUp, Copy, ExternalLink, Info, X,
} from 'lucide-react'
import { api, type Recommendation } from '@/lib/api'
import { creditsDelta, humanizeAgo } from '@/lib/format'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import {
  Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription,
  SheetBody, SheetFooter,
} from '@/components/ui/sheet'

export function RecommendationDrawer({
  recommendationId,
  onOpenChange,
}: {
  recommendationId: number | null
  onOpenChange: (open: boolean) => void
}) {
  const open = recommendationId != null
  return (
    <Sheet
      open={open}
      onOpenChange={(o) => {
        if (!o) onOpenChange(false)
      }}
    >
      <SheetContent>
        {recommendationId != null ? (
          <DrawerInner id={recommendationId} onClose={() => onOpenChange(false)} />
        ) : null}
      </SheetContent>
    </Sheet>
  )
}

function DrawerInner({ id, onClose }: { id: number; onClose: () => void }) {
  const q = useQuery({
    queryKey: ['recommendation', id],
    queryFn: () => api.getRecommendation(id),
    refetchOnWindowFocus: false,
  })

  if (q.isLoading) return <Loading />
  if (q.isError || !q.data) return <ErrorBlock />
  return <DrawerBody rec={q.data} onClose={onClose} />
}

function DrawerBody({ rec, onClose }: { rec: Recommendation; onClose: () => void }) {
  const qc = useQueryClient()
  const [showRollback, setShowRollback] = useState(false)
  const [copied, setCopied] = useState(false)

  const accept = useMutation({
    mutationFn: () => api.acceptRecommendation(rec.id ?? 0),
    onSuccess: () => {
      invalidate(qc)
      onClose()
    },
  })
  const reject = useMutation({
    mutationFn: () => api.rejectRecommendation(rec.id ?? 0),
    onSuccess: () => {
      invalidate(qc)
      onClose()
    },
  })

  const warehouseName = warehouseFromTarget(rec.target_resource)
  const cdd = rec.expected_impact?.credits_delta_daily ?? null
  const conf = rec.expected_impact?.confidence ?? 0
  const status = rec.status
  const isActionable = status === 'PROPOSED'

  function copyToClipboard(text: string) {
    navigator.clipboard
      .writeText(text)
      .then(() => {
        setCopied(true)
        setTimeout(() => setCopied(false), 1500)
      })
      .catch(() => undefined)
  }

  return (
    <>
      <SheetHeader>
        <div className="flex items-center gap-2 pr-8">
          <span className="font-mono text-xs text-muted-foreground">#{rec.id}</span>
          <SheetTitle className="text-lg">{rec.action_type}</SheetTitle>
          <StatusBadge status={status} />
        </div>
        <SheetDescription>
          on{' '}
          {warehouseName ? (
            <Link
              to="/warehouses/$name"
              params={{ name: warehouseName }}
              className="font-medium text-foreground underline-offset-4 hover:underline"
            >
              {warehouseName}
            </Link>
          ) : (
            <span className="font-medium text-foreground">{rec.target_resource ?? '—'}</span>
          )}{' '}
          · generated by{' '}
          <span className="font-mono">{rec.generated_by}</span>
          {rec.created_at && <> · {humanizeAgo(rec.created_at)}</>}
        </SheetDescription>
      </SheetHeader>

      <SheetBody className="space-y-6">
        <Section title="Preview">
          <pre className="overflow-x-auto rounded-md bg-muted/50 px-3 py-2 font-mono text-xs leading-relaxed">
            {rec.preview}
          </pre>
        </Section>

        <Section
          title="SQL to run"
          right={
            <Button
              variant="ghost"
              size="sm"
              onClick={() => copyToClipboard(rec.sql)}
              title="Copy to clipboard"
            >
              {copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
              {copied ? 'Copied' : 'Copy'}
            </Button>
          }
        >
          <pre className="overflow-x-auto rounded-md border bg-muted/30 px-3 py-2 font-mono text-xs leading-relaxed">
            {rec.sql}
          </pre>
        </Section>

        {rec.rollback_sql && (
          <Section
            title="Rollback SQL"
            right={
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setShowRollback((s) => !s)}
              >
                {showRollback ? (
                  <ChevronUp className="h-3.5 w-3.5" />
                ) : (
                  <ChevronDown className="h-3.5 w-3.5" />
                )}
                {showRollback ? 'Hide' : 'Show'}
              </Button>
            }
          >
            {showRollback && (
              <pre className="overflow-x-auto rounded-md border bg-muted/30 px-3 py-2 font-mono text-xs leading-relaxed">
                {rec.rollback_sql}
              </pre>
            )}
          </Section>
        )}

        <Section title="Rationale">
          <p className="whitespace-pre-line text-sm text-foreground/90">{rec.rationale}</p>
        </Section>

        {rec.evidence?.length > 0 && (
          <Section title="Evidence">
            <ul className="space-y-1.5 text-sm">
              {rec.evidence.map((ev, i) => (
                <li key={i} className="flex items-start gap-2 text-foreground/90">
                  <span className="mt-0.5 inline-block rounded bg-muted px-1.5 py-0.5 font-mono text-[10px] uppercase tracking-wide text-muted-foreground">
                    {ev.kind}
                  </span>
                  <span className="flex-1">
                    {ev.description}
                    {ev.metric && ev.value != null && (
                      <span className="ml-2 font-mono text-xs text-muted-foreground tabular-nums">
                        {ev.metric}={String(ev.value)}
                      </span>
                    )}
                  </span>
                </li>
              ))}
            </ul>
          </Section>
        )}

        <Section title="Expected impact">
          <div className="grid grid-cols-2 gap-4">
            <div>
              <div className="text-xs uppercase tracking-wide text-muted-foreground">
                Confidence
              </div>
              <div className="mt-1 text-xl font-semibold tabular-nums">{(conf * 100).toFixed(0)}%</div>
            </div>
            <div>
              <div className="text-xs uppercase tracking-wide text-muted-foreground">
                Daily credit delta
              </div>
              <div className="mt-1 text-xl font-semibold tabular-nums">
                {creditsDelta(cdd)}
              </div>
            </div>
          </div>
          {rec.expected_impact?.notes && (
            <p className="mt-3 flex items-start gap-2 text-xs text-muted-foreground">
              <Info className="mt-0.5 h-3 w-3 shrink-0" />
              <span>{rec.expected_impact.notes}</span>
            </p>
          )}
        </Section>
      </SheetBody>

      <SheetFooter>
        {warehouseName && (
          <Button asChild variant="ghost" size="sm" className="mr-auto">
            <Link
              to="/warehouses/$name"
              params={{ name: warehouseName }}
              onClick={onClose}
            >
              <ExternalLink className="h-3.5 w-3.5" /> Open in warehouse view
            </Link>
          </Button>
        )}
        {isActionable ? (
          <>
            <Button
              variant="ghost"
              size="sm"
              onClick={() => reject.mutate()}
              disabled={reject.isPending || accept.isPending}
            >
              <X className="h-3.5 w-3.5" /> Reject
            </Button>
            <Button
              variant="default"
              size="sm"
              onClick={() => accept.mutate()}
              disabled={reject.isPending || accept.isPending}
            >
              <Check className="h-3.5 w-3.5" />{' '}
              {accept.isPending ? 'Accepting…' : 'Accept'}
            </Button>
          </>
        ) : (
          <Button variant="outline" size="sm" onClick={onClose}>
            Close
          </Button>
        )}
      </SheetFooter>
    </>
  )
}

function Section({
  title,
  children,
  right,
}: {
  title: string
  children: React.ReactNode
  right?: React.ReactNode
}) {
  return (
    <section>
      <div className="mb-2 flex items-center justify-between">
        <h3 className="text-xs uppercase tracking-wide text-muted-foreground">{title}</h3>
        {right}
      </div>
      {children}
    </section>
  )
}

function StatusBadge({ status }: { status: string }) {
  const variant: 'default' | 'success' | 'warning' | 'destructive' | 'secondary' | 'outline' =
    status === 'APPLIED' ? 'success'
    : status === 'ROLLED_BACK' ? 'warning'
    : status === 'REJECTED' ? 'destructive'
    : status === 'SUPERSEDED' ? 'secondary'
    : 'outline'
  return (
    <Badge variant={variant} className="text-[10px] uppercase tracking-wide">
      {status}
    </Badge>
  )
}

function Loading() {
  return (
    <>
      <SheetHeader>
        <SheetTitle>
          <span className="inline-block h-5 w-32 animate-pulse rounded bg-muted" />
        </SheetTitle>
        <SheetDescription>
          <span className="inline-block h-3 w-48 animate-pulse rounded bg-muted" />
        </SheetDescription>
      </SheetHeader>
      <SheetBody className="space-y-4">
        <div className="h-4 w-1/2 animate-pulse rounded bg-muted" />
        <div className="h-20 animate-pulse rounded bg-muted" />
        <div className="h-4 w-1/3 animate-pulse rounded bg-muted" />
        <div className="h-12 animate-pulse rounded bg-muted" />
      </SheetBody>
    </>
  )
}

function ErrorBlock() {
  return (
    <SheetBody>
      <div className="flex items-start gap-3 rounded-md border border-destructive/40 p-4">
        <AlertCircle className="mt-0.5 h-4 w-4 text-destructive" />
        <div>
          <div className="font-medium">Couldn't load recommendation</div>
          <p className="mt-1 text-sm text-muted-foreground">
            It may have been superseded or the API may be unreachable.
          </p>
        </div>
      </div>
    </SheetBody>
  )
}

function warehouseFromTarget(target: string | null | undefined): string | null {
  if (!target) return null
  const m = target.match(/^warehouse:([^:]+)/)
  return m ? m[1] : null
}

function invalidate(qc: ReturnType<typeof useQueryClient>) {
  qc.invalidateQueries({ queryKey: ['recommendations'] })
  qc.invalidateQueries({ queryKey: ['recommendation'] })
  qc.invalidateQueries({ queryKey: ['warehouses'] })
  qc.invalidateQueries({ queryKey: ['status'] })
}
